print("." * 40)
print("Tugas 1 SISOP Kelas-B")
print("." * 40)
print("Nama : Rheinka Elyana S.")
print("NPM : 21083010021")
print("." * 40)
print("notes: ")
print("." * 40)
print("Halo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux!")

